package cn.superfw.application.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * Model class of 账户.
 *
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@DynamicUpdate(true)
@DynamicInsert(true)
@Table(name="t_account")
public class Account extends BaseEntity implements Serializable {

    /** serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** 用户名. */
    private String username;

    /** 密码. */
    private String password;

    /** 电子邮件. */
    private String email;

    /** 账户状态. */
    private String state;

    /** 上次登录时间. */
    private Date lastLogonTime;

    /** 登录次数. */
    private Long logonCount;

    private Set<Role> roleSet;

    /** 头像. */
    private String headPic;

    /** 昵称. */
    private String nickname;

    /** 部门 */
    private String dept;

    /** 职位 */
    private String position;

	/**
     * Constructor.
     */
    public Account() {
        this.roleSet = new HashSet<Role>();
    }

    /**
     * Set the 用户名.
     *
     * @param username
     *            用户名
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Get the 用户名.
     *
     * @return 用户名
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Set the 密码.
     *
     * @param password
     *            密码
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Get the 密码.
     *
     * @return 密码
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Set the 账户状态.
     *
     * @param state
     *            账户状态
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * Get the 账户状态.
     *
     * @return 账户状态
     */
    public String getState() {
        return this.state;
    }

    /**
     * Set the 上次登录时间.
     *
     * @param lastLogonTime
     *            上次登录时间
     */
    public void setLastLogonTime(Date lastLogonTime) {
        this.lastLogonTime = lastLogonTime;
    }

    /**
     * Get the 上次登录时间.
     *
     * @return 上次登录时间
     */
    public Date getLastLogonTime() {
        return this.lastLogonTime;
    }

    /**
     * Set the 登录次数.
     *
     * @param logonCount
     *            登录次数
     */
    public void setLogonCount(Long logonCount) {
        this.logonCount = logonCount;
    }

    /**
     * Get the 登录次数.
     *
     * @return 登录次数
     */
    public Long getLogonCount() {
        return this.logonCount;
    }

    @ManyToMany(cascade={CascadeType.PERSIST, CascadeType.REFRESH})
    @JoinTable(name="m_account_role",joinColumns={@JoinColumn(name="account_id")},
    inverseJoinColumns={@JoinColumn(name="role_id")})
    public Set<Role> getRoleSet() {
        return roleSet;
    }
    public void setRoleSet(Set<Role> roleSet) {
        this.roleSet = roleSet;
    }
    public void addRole(Role role) {
        this.roleSet.add(role);
    }

    /**
     * 取得headPic.
     * @return the headPic
     */
    public String getHeadPic() {
        return headPic;
    }


    /**
     * 设定headPic
     * @param headPic the headPic to set
     */
    public void setHeadPic(String headPic) {
        this.headPic = headPic;
    }

    /**
     * Set the 昵称.
     *
     * @param nickname
     *            昵称
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * Get the 昵称.
     *
     * @return 昵称
     */
    public String getNickname() {
        return this.nickname;
    }

    /**
     * Get the 职位.
     *
     * @return 职位
     */
    public String getPosition() {
		return position;
	}

    /**
     * Set the 职位.
     *
     * @param position
     *            职位
     */
	public void setPosition(String position) {
		this.position = position;
	}


    public String getDept() {
		return dept;
	}

	public void setDept(String dept) {
		this.dept = dept;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	/**
     * {@inheritDoc}
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        Account other = (Account) obj;
        if (getId() == null) {
            if (other.getId() != null) {
                return false;
            }
        } else if (!getId().equals(other.getId())) {
            return false;
        }
        return true;
    }

}
