package cn.superfw.application.domain;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Model class of 编码一览.
 *
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name = "m_code")
public class Code extends BaseEntity implements Serializable {

    /** serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** 分类ID. [口味:01][难度:02][工艺:03][时间:04] */
    private String typeId ;

    /** 分类名称. [口味:01][难度:02][工艺:03][时间:04] */
    private String typeName ;

    /** 编码ID. */
    private String codeId;

    /** 编码名称. */
    private String codeName;

    /** 排序字段. */
    private Integer sortitem;

    /**
     * Constructor.
     */
    public Code() {
    }

    /**
     * Set the 分类ID.
     *
     * @param typeId
     *            分类ID
     */
    public void setTypeId (String typeId ) {
        this.typeId  = typeId ;
    }

    /**
     * Get the 分类ID.
     *
     * @return 分类ID
     */
    public String getTypeId () {
        return this.typeId ;
    }

    /**
     * Set the 编码ID.
     *
     * @param codeId
     *            编码ID
     */
    public void setCodeId(String codeId) {
        this.codeId = codeId;
    }

    /**
     * Get the 编码ID.
     *
     * @return 编码ID
     */
    public String getCodeId() {
        return this.codeId;
    }

    /**
     * Set the 编码名称.
     *
     * @param codeName
     *            编码名称
     */
    public void setCodeName(String codeName) {
        this.codeName = codeName;
    }

    /**
     * Get the 编码名称.
     *
     * @return 编码名称
     */
    public String getCodeName() {
        return this.codeName;
    }

    /**
     * Get the 分类名称.
     *
     * @return 分类名称
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * Set the 分类名称.
     *
     * @param typeName
     *            分类名称
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * Set the 排序字段.
     *
     * @param sortitem
     *            排序字段
     */
    public void setSortitem(Integer sortitem) {
        this.sortitem = sortitem;
    }

    /**
     * Get the 排序字段.
     *
     * @return 排序字段
     */
    public Integer getSortitem() {
        return this.sortitem;
    }

}
